version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - trussworks/waddlers
  labels:
  - dependencies
  ignore:
  - dependency-name: github.com/gruntwork-io/terratest
    versions:
    - 0.31.5
    - 0.32.1
    - 0.32.10
    - 0.32.15
    - 0.32.18
    - 0.32.20
    - 0.32.21
    - 0.32.24
    - 0.32.3
    - 0.32.5
    - 0.32.7
    - 0.32.8
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.36.31
    - 1.37.1
    - 1.37.10
    - 1.37.15
    - 1.37.20
    - 1.37.25
    - 1.37.30
    - 1.37.6
    - 1.38.1
    - 1.38.12
    - 1.38.17
    - 1.38.21
    - 1.38.7
